[build]
  publish = "build/client"

# Ensure SPA fallback for client-side routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
